config/routes.rb
ClassSchedulerApp::Application.routes.draw do

  devise_for :users

  get '/redraw_calendar', to: 'dashboard#redraw_calendar', as: 'redraw_calendar'

  resources :dashboard

  resources :bookings

  resources :locations do
    resources :classrooms
  end

  resources :courses do
    resources :cohorts do
      resources :enrollments
      resources :instructor_assignments
    end
  end

  resources :users

  root to: 'dashboard#index'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    redirect_to login_path unless current_user
    @locations = Location.all
    @courses = Course.all
    @users = User.all

    # for the calendar plugin
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end

  def redraw_calendar
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @classroom = params[:classroom_id]

    respond_to do |format|
      format.js
    end
  end

end

app/views/dashboard/_courses.html.erb
<h2 id='dash_port_title'>GA Courses</h2>

<% if can? :manage, Course %>
  <div id='add_new_button'>
  <%= button_to 'Add New Course', new_course_path, method: :get, class: 'btn btn-default btn-xs' %>
  </div>
<% end %>

<section id='locations'>
  <% @courses.each do |course| %>
  <div class='location_port'>

    <h3><%= course.name %></h3>
    <div id='location_details'>
      <p>Duration: <%= course.duration_weeks %> weeks</p>
      <p>Price: <%= number_to_currency(course.price, unit: "£") %> </p>
      <p>Minimum Instructors: <%= course.instructors_req %></p>
    </div>

    <% course.cohorts.each do |cohort| %>
    <div class='course_cohort_port'>
      <h4><%= link_to "#{cohort.name}",course_cohort_path(course, cohort)%></h4>
      <p>Start Date: <%= cohort.if_booked %></p>
      <p>Assigned Instructors: <%= cohort.instructors.count %></p>
      <p>Enrolled Students: <%= cohort.students.count %></p>

    </div>
    <% end %>

    <div class='port_buttons'>
      <% if can? :manage, Course %>
        <%= button_to 'Add Cohort', new_course_cohort_path(course), method: :get, class: 'btn btn-default btn-xs btn-long' %>
        <%= button_to 'Edit', edit_course_path(course), method: :get, class: 'btn btn-default btn-xs' %>
        <%= button_to 'Delete', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
      <% end %>
    </div>

  </div>
  <% end %>
</section>

app/views/dashboard/_locations.html.erb
<h2 id='dash_port_title'>GA Locations</h2>

<% if can? :manage, Location %>
  <div id='add_new_button'>
  <%= button_to 'Add New Location', new_location_path, method: :get, class: 'btn btn-default btn-xs' %>
  </div>
<% end %>

<section id='locations'>
  <% @locations.each do |location| %>
  <div class='location_port'>
    
    <h3><%= location.name %></h3>
    <div id='location_details'>
    </div>

    <% location.classrooms.each do |classroom| %>
    <div class='location_classroom_port'>
      <h4><%= link_to "#{classroom.name}",location_classroom_path(location, classroom)%></h4>
      <p>Capacity: <%= classroom.capacity %></p>
      <p>Facilities: <%= classroom.facilities %></p>
      <p>Total Bookings: <%= classroom.bookings.count %></p>
    </div>
    <% end %>

    <div class='port_buttons'>
      <% if can? :manage, Location %>
        <%= button_to 'Add Classroom', new_location_classroom_path(location), method: :get, class: 'btn btn-default btn-xs btn-long' %>
        <%= button_to 'Edit', edit_location_path(location), method: :get, class: 'btn btn-default btn-xs' %>
        <%= button_to 'Delete', location, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
      <% end %>
    </div>

  </div>
  <% end %>
</section>

app/views/dashboard/_new_booking.html.erb
<h2><small>New Booking</small></h2>

<div id='classroom_calendar'>
<%= render 'classrooms/calendar' %>
</div>

<%= form_tag(new_booking_path, method: 'get') do %>

  <div class='form-group booking_req'>
    <%= label_tag(:classroom_id) %><br>
    <%= collection_select(:booking, :classroom_id, Classroom.all, :id, :details) %>
  </div>

  <div class='form-group booking_req'>
    <%= label_tag(:cohort_id) %><br>
    <%= collection_select(:booking, :cohort_id, Cohort.all, :id, :name) %>
  </div>

  <div class='actions booking_req'>
    <%= submit_tag 'Add Booking', :class => 'btn btn-default btn-xs' %>
  </div>

<% end %>

<div style="clear: both;"></div>

app/views/dashboard/_users.html.erb
<h2 id='dash_port_title'>GA Users</h2>

<% if can? :manage, User %>
  <div id='add_new_button'>
  <%= button_to 'Add New User', new_user_path, method: :get, class: 'btn btn-default btn-xs' %>
  </div>
<% end %>

<section id='users_table'>
  <table class='table table-striped'>

    <col class='col_user_name'/>
    <col class='col_user_email'/>
    <col class='col_user_cohorts'/>
    <col class='col_user_role'/>
    <col class='col_user_actions'/>

    <tr>
      <th>Name</th>
      <th>E-Mail</th>
      <th>Current Cohorts</th>
      <th>System Role</th>
      <th><!-- Actions --></th>
    </tr>
    <div id="users">
      <%= render @users %>
    </div>
  </table>
</section>

app/views/dashboard/index.html.erb
<% if can? :read, Booking %>
  <h2>Bookings</h2>

  <div id='view_bookings_button_frame'>
    <% if can? :manage, Booking %>
      <button class='btn btn-success btn-xs booking_req' id="new_bookings_button">Add Booking</button>
    <% end %>
    <%= link_to 'View Bookings', bookings_path, class: 'btn btn-default btn-xs booking_req', id: "view_bookings_button" %>
  </div>

  <% if can? :manage, Booking %>
  <div id='dash_new_booking_port'>
    <%= render 'new_booking' %>
  </div>
  <% end %>
<% end %>

<% if can? :read, Location %>
  <%= render 'locations' %>
<% end %>

<% if can? :read, Course %>
  <%= render 'courses' %>
<% end %>

<%= render 'users' %>

app/views/dashboard/redraw_calendar.js.erb
var calendarHTML = "<%= escape_javascript(render 'classrooms/calendar' ) %>";

$('#classroom_calendar').html(calendarHTML);