config/routes.rb
ClassSchedulerApp::Application.routes.draw do

  devise_for :users

  get '/redraw_calendar', to: 'dashboard#redraw_calendar', as: 'redraw_calendar'

  resources :dashboard

  resources :bookings

  resources :locations do
    resources :classrooms
  end

  resources :courses do
    resources :cohorts do
      resources :enrollments
      resources :instructor_assignments
    end
  end

  resources :users

  root to: 'dashboard#index'

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :cohort
  belongs_to :classroom
  attr_accessible :end_date, :start_date, :cohort_id, :classroom_id

  def cohort_students
    cohort.students.count
  end

  def cohort_instructors
    cohort.instructors.count
  end

  def class_size
    cohort_instructors + cohort_students
  end

  def if_intended_start
    intended_start = cohort.start_date
    if intended_start
      intended_start
    else
      lambda {Date.now}
    end
  end

  def name
    cohort.name
  end

  def covers_date?(date)
    (start_date..end_date).cover?(date)
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  load_and_authorize_resource :booking

  def index
    @classrooms = Classroom.all

    # for the calendar plugin
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end

  def new
    @booking = Booking.new(params[:booking])
    @classroom = @booking.classroom
    @cohort = @booking.cohort
  end

  def create
    start_date = (params[:booking])[:start_date]
    cohort = Cohort.find((params[:booking])[:cohort_id])
    course_duration = cohort.course.duration_weeks
    params[:booking][:end_date] = start_date.to_date + ( course_duration * 7).days

    @booking = Booking.new(params[:booking])

    if @booking.save
      redirect_to bookings_path, notice: 'Classroom was successfully created.' 
    else
      render action: "new" 
    end
  end

  def edit
    @booking = Booking.find(params[:id])
    @classroom = @booking.classroom
    @cohort = @booking.cohort
    @booking_req = {cohort_id: @booking.cohort_id, classroom_id: @booking.classroom_id}
  end

  def update
    @booking = Booking.find(params[:id])

    if @booking.update_attributes(params[:booking])
      redirect_to bookings_path, notice: 'Location was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

    redirect_to bookings_path
  end
end

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group'>
    <%= f.label :start_date %><br>
    <%= f.date_field :start_date, :value => @booking.if_intended_start %>
  </div>

  <%= f.hidden_field(:cohort_id, :value => @booking.cohort_id) %>
  <%= f.hidden_field(:classroom_id, :value => @booking.classroom_id) %>

  <div class="actions">
    <%= f.submit :class => 'btn btn-default btn-xs' %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Edit Your Booking <small>- <%= @classroom.details %> | <%= @cohort.name %></small></h1>

<p>Course duration requirement: <%= @cohort.course.duration_weeks %></p>
<p>Cohort intended start date: <%= @cohort.start_date %></p>

<%= render 'form' %>

<%= link_to 'Back', dashboard_index_path %>

app/views/bookings/index.html.erb
<h2>GA Bookings</h2>

<%= render '/dashboard/new_booking' %>

<% @classrooms.each do |classroom| %>
<div class='booking_index_classrooms'>
  <% if !classroom.bookings.empty? %>
    <h3><%= classroom.details %></h3>

    <% classroom.bookings.each do |booking| %>
      <div class='booking_index_booking'>
        <h4><%= booking.cohort.name %></h4>
        <p>Start Date: <%= booking.start_date %></p>
        <p>End Date: <%= booking.end_date %></p>
        <p>Booking Capacity: <%= booking.class_size %> / <%= classroom.capacity %> <br><small>(<%= booking.cohort_instructors %> Instructors, <%= booking.cohort_students %> Students)</small></p>

        <%= button_to 'Edit', edit_booking_path(booking), method: :get, class: 'btn btn-default btn-xs' %>
        <%= button_to 'Delete', booking, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
      </div>
    <% end %>
  <% end %>
</div>
<% end %>

<%= link_to 'Back', dashboard_index_path %>

app/views/bookings/new.html.erb
<h1>Add a New Booking <small>- <%= @classroom.details %> | <%= @cohort.name %></small></h1>

<p>Course duration requirement: <%= @cohort.course.duration_weeks %></p>
<p>Cohort intended start date: <%= @cohort.start_date %></p>

<%= render 'form' %>

<%= link_to 'Back', dashboard_index_path %>