config/routes.rb
ClassSchedulerApp::Application.routes.draw do

  devise_for :users

  get '/redraw_calendar', to: 'dashboard#redraw_calendar', as: 'redraw_calendar'

  resources :dashboard

  resources :bookings

  resources :locations do
    resources :classrooms
  end

  resources :courses do
    resources :cohorts do
      resources :enrollments
      resources :instructor_assignments
    end
  end

  resources :users

  root to: 'dashboard#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Classkeeper</title>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'GA Classkeeper', dashboard_index_path, class: "navbar-brand" %>
          <% if current_user %>
            <span class="navbar-text"><small>Logged in as <%= current_user.name %> <%= "| " + current_user.role.capitalize if current_user.role %></small></span>
          <% end %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Dashboard', dashboard_index_path %></li>
            <% if current_user %>
              <li><%= link_to 'Profile', edit_user_registration_path %><li>
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Login", new_user_session_path %></li>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
      <% flash.each do |name, message| %>
        <div class='flash-message'>
          <p><%= message %></p>
          <%#= notice %>
          <%#= alert %>
        </div>
      <% end %>
    </div>

  </header>

  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3 col-md-2 sidebar">
        <ul class="nav nav-sidebar">
          <li class="active"><%= link_to 'Dashboard Home', dashboard_index_path %></li>
          <li><%= link_to 'Locations', locations_path %></li>
          <li><%= link_to 'Courses', courses_path %></li>
        </ul>
        <ul class="nav nav-sidebar">
          <li><%= link_to 'Users', users_path %></li>
          <%= form_tag users_path, method: :get, remote: true, id: "search_form", class: "navbar-form" do %>
            <div class="form-group">
              <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search Users..." %>
            </div>
          <% end %>
        </ul>
        <ul class="nav nav-sidebar">
          <li><h3>Current Info</h3></li>
          <li><p>Statistic 1</p></li>
          <li><p>Statistic 2</p></li>
        </ul>
        <ul class="nav nav-sidebar">
          <li><h3>Admin Notes</h3></li>
          <li><p>Note 1</p></li>
          <li><p>Note 2</p></li>
        </ul>
      </div>
      <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1 class="page-header">GA Dashboard</h1>

        <%= yield %>

      </div>
    </div>
  </div>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Classkeeper</title>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'GA Classkeeper', dashboard_index_path, class: "navbar-brand" %>
          <% if current_user %>
            <span class="navbar-text"><small>Logged in as <%= current_user.name %> <%= "| " + current_user.role.capitalize if current_user.role %></small></span>
          <% end %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Dashboard', dashboard_index_path %></li>
            <% if current_user %>
              <li><%= link_to 'Profile', edit_user_registration_path %><li>
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Login", new_user_session_path %></li>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
      <% flash.each do |name, message| %>
        <div class='flash-message'>
          <p><%= message %></p>
          <%#= notice %>
          <%#= alert %>
        </div>
      <% end %>
    </div>

  </header>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>